name: release
on:
  push:
    branches:
      - release**
  pull_request:
    branches:
      - release**
defaults:
  run:
    shell: bash
jobs:
  integration:
    name: integration
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v6.0.2
      - name: Set up uv
        id: setup-uv
        uses: astral-sh/setup-uv@v7.2.0
        with:
          python-version: '3.14'
          enable-cache: true
          activate-environment: true
          cache-dependency-glob: |
            requirements/required.txt
            requirements/datasets.txt
            requirements/tests.txt
      - name: Install pip dependencies
        run: |
          uv pip install .[datasets,tests]
      - name: List pip dependencies
        run: uv pip list
      - name: Run integration checks
        run: |
          uv run --no-sync pytest -m slow --durations=10 tests/samplers
          uv run --no-sync pytest -m slow --durations=10 tests/trainers
          uv run --no-sync python -m torchgeo --help
          uv run --no-sync torchgeo --help
  notebooks:
    name: notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v6.0.2
      - name: Set up uv
        id: setup-uv
        uses: astral-sh/setup-uv@v7.2.0
        with:
          python-version: '3.14'
          enable-cache: true
          activate-environment: true
          cache-dependency-glob: |
            requirements/required.txt
            requirements/docs.txt
            requirements/tests.txt
      - name: Install pip dependencies
        run: |
          uv pip install .[docs,tests] planetary_computer pystac tensorboard h5py scikit-learn
      - name: List pip dependencies
        run: uv pip list
      - name: Run notebook checks
        run: uv run --no-sync pytest --nbmake --durations=10 docs/tutorials
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
